Healthie errors
awell-health/awell-extensions pull request #160
Opened 2023-06-14 10:07 UTC by michal-grzelak

Closes #158 

- Implement error throwing for graphql inside the client
- Handle healthie errors for all healthie actions

2023-06-14 18:01 UTC, nckhell approved these changes
@michal-grzelak At first sight it looks good. However, I would be more comfortable if there's a test that asserts whether your error middleware works as expected for 1 use case (eg: create task).

Writing tests for all the actions is probably overkill, but a more generic test might not be a bad idea. WDYT?

2023-06-15 05:38 UTC, michal-grzelak commented
@nckhell 
> @michal-grzelak At first sight it looks good. However, I would be more comfortable if there's a test that asserts whether your error middleware works as expected for 1 use case (eg: create task).
> 
> Writing tests for all the actions is probably overkill, but a more generic test might not be a bad idea. WDYT?

Sure, I will go right to it 👍🏻

2023-06-15 08:12 UTC, nckhell requested changes

2023-06-15 08:12 UTC, nckhell commented on extensions/healthie/actions/__tests__/errors.ts
> +        'Error in Healthie: invalid object name or field, or a record is not found.',
@michal-grzelak Is it possible to grab the actual error message? In this case, I'd expect we throw an error with the following messag: `You do not have permission to create this task.`

2023-06-15 08:27 UTC, nckhell approved these changes

2023-06-15 08:27 UTC, nckhell approved these changes

2023-06-15 08:28 UTC, merged