feat(wellinks-extension): Adds a new action to check if a Flourish Customer exists
awell-health/awell-extensions pull request #251
Opened 2023-09-12 22:07 UTC by AshvinP-S

- Customer is found by matching Healthie ID to ThirdPartyIdentifier

2023-09-14 10:34 UTC, bejoinka requested changes
Should be good after removing the try/catch!

2023-09-14 10:34 UTC, bejoinka commented on extensions/wellinks/actions/checkFlourishCustomer/checkFlourishCustomer.ts
> +      if (err instanceof ZodError) {
We already handle zod errors in our server --> no need for you to catch them unless you want to display something other than information about the incorrect validation

2023-09-14 10:34 UTC, bejoinka commented on extensions/wellinks/actions/checkFlourishCustomer/checkFlourishCustomer.ts
> +      if (err instanceof ZodError) {
i suggest you remove the entire try/catch mechanism here, given we will already know which activity throws the error.

2023-09-14 10:34 UTC, bejoinka commented on extensions/wellinks/actions/checkFlourishCustomer/checkFlourishCustomer.test.ts
> +    expect(onError).toHaveBeenNthCalledWith(1, {
given my comment about removing the entire try/catch, you can just make sure the error thrown is a ZodError

2023-09-14 10:34 UTC, bejoinka commented on extensions/wellinks/actions/checkFlourishCustomer/checkFlourishCustomer.test.ts
> +    expect(onError).toHaveBeenNthCalledWith(1, {
given my comment about removing the entire try/catch, you can just make sure the error thrown is a ZodError

2023-09-14 10:34 UTC, bejoinka commented on extensions/wellinks/actions/checkFlourishCustomer/config/settings.ts
the settings should be at the extension level (and not the action level), right?

2023-09-14 17:32 UTC, AshvinP-S commented on extensions/wellinks/actions/checkFlourishCustomer/config/settings.ts
This action specifically requires a setting that is otherwise not required, so rather than making that setting required across the extension, I added this schema at the action level to make sure that the setting is defined only for this action. Does that make sense?

2023-09-16 22:34 UTC, bejoinka commented on extensions/wellinks/actions/checkFlourishCustomer/config/settings.ts
per convo in slack, makes perf sense you refactor once you use zod elsewhere

2023-09-16 22:36 UTC, bejoinka approved these changes
much cleaner. makes me happy.

2023-09-16 22:36 UTC, merged