[EXT-50] New extension: Zus Health
awell-health/awell-extensions pull request #263
Opened 2023-09-26 14:24 UTC by kubiak85

null

<sub>[EXT-60](https://linear.app/awell/issue/EXT-60/[ext-50]-new-extension-zus-health)</sub>

2023-09-26 15:18 UTC, rahulkeerthi requested changes

2023-09-27 08:07 UTC, kubiak85 commented on extensions/zusHealth/webhooks/getResource.ts
@rahulkeerthi Two webhooks with the same functionality?

2023-09-27 10:41 UTC, rahulkeerthi commented on extensions/zusHealth/webhooks/getResource.ts
@kubiak85 sorry, I did say two different things -- let me try again!

- yes, two webhooks, patientAdmitted and patientDischarged
- in patientAdmitted, we do the same until we have the Encounter fetched then we check the status. If it is not an admit event (using the logic above) then we do nothing, and if it is, we start a care flow (onSuccess)
- in patientDischarged, same as above but we check if it is a discharge event (using conditions above) and same, do nothing if it is not and start a care flow if it is a discharge

2023-09-27 12:31 UTC, rahulkeerthi requested changes

2023-09-27 12:31 UTC, rahulkeerthi commented on extensions/zusHealth/README.md
> +[ZUS Health](https://zushealth.com/) is the only shared health data platform designed to accelerate healthcare data interoperability by providing easy-to-use patient data at the point of care via API
```suggestion
[Zus Health](https://zushealth.com/) is the only shared health data platform designed to accelerate healthcare data interoperability by providing easy-to-use patient data at the point of care via API, embedded components, and direct EHR integrations.
```

2023-09-27 12:54 UTC, rahulkeerthi commented on extensions/zusHealth/webhooks/patientAdmitted.ts
> +            userId: payload.ownerId,
see next comment

2023-09-27 13:04 UTC, rahulkeerthi approved these changes

2023-09-27 13:34 UTC, merged