feat(healthie): Add checkPatientTag action
awell-health/awell-extensions pull request #321
Opened 2024-01-28 00:20 UTC by danijel

Add checkPatientTag healthie action that checks does patient has an active tag with id

2024-01-28 12:16 UTC, danijel commented
@bejoinka, @ebomcke-awell  tests a failing because the addition of the external-server, I think there is some issues with the naming of this extension and it's action.

I see this was added recently but I don't know what is the purpose of this, is this even used, can it be disabled. We need these two healthie actions for bootcamp with a customer

2024-01-29 09:52 UTC, ebomcke-awell requested changes
I find the pattern used for test pretty confusing. Reading the tests themselves it's not immediately apparent why the result of `onComplete` changes in the different test scenarios. It's only when looking at the mock SDK file that it becomes clear: it uses the input payload to conditionally generate API responses.
This is not great as it makes tests less understandable and harder to maintain because of the semi-hidden dependency to the mock SDK logic.

Defining the mock implementation inside the test file would make this much clearer. Not necessarily needed for this PR though, I'm mentioning this for future reference.

The description changes on the other hand are required as they show up in Studio.

2024-01-29 09:52 UTC, ebomcke-awell commented on extensions/healthie/actions/checkPatientTag/checkPatientTag.ts
> +  description: 'Check is tag applied as active tag on patient in Healthie.',
```suggestion
  description: 'Check if a patient has the given tag in their active tags in Healthie.',
```

2024-01-29 09:52 UTC, ebomcke-awell commented on extensions/healthie/actions/checkScheduledAppointments/checkScheduledAppointments.ts
> +    'Check does the patient have active appointment scheduled for an appointment type',
```suggestion
    'Check if the given patient has an active appointment scheduled for the given appointment type.',
```

2024-01-29 10:02 UTC, merged